/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-03-22 02:37:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import data.dto.MemberDto;
import java.util.List;
import data.dao.MemberDao;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("data.dao.MemberDao");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("data.dto.MemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Dongle&family=Gaegu&family=Nanum+Pen+Script&family=Noto+Sans+KR:wght@100..900&family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("  #mainimg{\r\n");
      out.write("		  width:100px;\r\n");
      out.write("		  height:100px;\r\n");
      out.write("		  border-radius: 100px;\r\n");
      out.write("		  margin-top: 30px;\r\n");
      out.write("		  margin-left: 20px;\r\n");
      out.write("		  border: 1px solid tomato;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  function delfunc(num){\r\n");
      out.write("	  //alert(num);\r\n");
      out.write("	  $(\"#delnum\").val(num);\r\n");
      out.write("	  $(\"#myModal\").modal('show');\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	  //삭제버튼이벤트\r\n");
      out.write("	  $(\"button.btndel\").click(function(){\r\n");
      out.write("		  \r\n");
      out.write("		  //num,pass읽기\r\n");
      out.write("		  var num=$(\"#delnum\").val();\r\n");
      out.write("		  var pass=$(\"#delpass\").val();\r\n");
      out.write("		  \r\n");
      out.write("		  //alert(num+\",\"+pass);\r\n");
      out.write("		  //삭제파일 호출\r\n");
      out.write("		  location.href=\"member/deletemypage.jsp?num=\"+num+\"&pass=\"+pass;\r\n");
      out.write("		  \r\n");
      out.write("	  })\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");

  MemberDao dao=new MemberDao();
  List<MemberDto> list=dao.getAllMembers();
  SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
  
  String loginok=(String)session.getAttribute("loginok");
  String myid=(String)session.getAttribute("myid");

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div  style=\"margin: 200px 100px; width: 800px;\">\r\n");
      out.write("       <table class=\"table table-bordered\">\r\n");
      out.write("         ");

           for(MemberDto dto:list)
           {
             if(loginok!=null && myid.equals(dto.getId())){
           
      out.write("\r\n");
      out.write("        	   <tr>\r\n");
      out.write("        	     <td rowspan=\"6\" align=\"center\" valign=\"middle\" style=\"width: 200px;\">\r\n");
      out.write("        	        <img src=\"image/shopimg.png\" id=\"mainimg\">\r\n");
      out.write("        	     </td>\r\n");
      out.write("        	     <td style=\"width: 300px;\">회원명: ");
      out.print(dto.getName() );
      out.write("</td>\r\n");
      out.write("        	     <td rowspan=\"6\" style=\"width: 150px;\" align=\"center\" valign=\"middle\">\r\n");
      out.write("        	        <button type=\"button\" class=\"btn btn-outline-info\"\r\n");
      out.write("        	        onclick=\"location.href='index.jsp?main=member/updatepassform.jsp?num=");
      out.print(dto.getNum());
      out.write("'\">수정</button><br><br>\r\n");
      out.write("        	        <button type=\"button\" class=\"btn btn-outline-danger\" onclick=\"delfunc('");
      out.print(dto.getNum());
      out.write("')\">탈퇴</button>\r\n");
      out.write("        	     </td>\r\n");
      out.write("        	   </tr>\r\n");
      out.write("        	   <tr>\r\n");
      out.write("        	     <td>아이디: ");
      out.print(dto.getId() );
      out.write("</td>\r\n");
      out.write("        	   </tr>\r\n");
      out.write("        	   <tr>\r\n");
      out.write("        	     <td>이메일: ");
      out.print(dto.getEmail() );
      out.write("</td>\r\n");
      out.write("        	   </tr>\r\n");
      out.write("        	   <tr>\r\n");
      out.write("        	     <td>핸드폰: ");
      out.print(dto.getHp() );
      out.write("</td>\r\n");
      out.write("        	   </tr>\r\n");
      out.write("        	   <tr>\r\n");
      out.write("        	     <td>주소: ");
      out.print(dto.getAddr() );
      out.write("</td>\r\n");
      out.write("        	   </tr>\r\n");
      out.write("        	   <tr>\r\n");
      out.write("        	     <td>가입일: ");
      out.print(sdf.format(dto.getGaipday()) );
      out.write("</td>\r\n");
      out.write("        	   </tr>\r\n");
      out.write("           ");
}
         
      out.write("\r\n");
      out.write("         \r\n");
      out.write("        ");
  }
      out.write("\r\n");
      out.write("       </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- The Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("  <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("    <div class=\"modal-content \">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">삭제확인</h4>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body d-inline-flex\">\r\n");
      out.write("        <input type=\"hidden\" id=\"delnum\">\r\n");
      out.write("        <b>삭제비밀번호: </b>\r\n");
      out.write("        <input type=\"password\" id=\"delpass\" class=\"form-control\" style=\"width: 120px; margin-left: 10px;\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger btndel\" data-bs-dismiss=\"modal\">삭제</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
